
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTSLAVE2_H
#define TESTSLAVE2_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestSlave2_valueRangeTest (UNS8 typeValue, void * value);
const indextable * TestSlave2_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data TestSlave2_Data;
extern UNS8 Slave2Map1_test;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS8 Slave2Map2_test;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS8 Slave2Map3_test;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS8 Slave2Map4_test;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS8 Slave2Map5_test;		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS8 Slave2Map6_test;		/* Mapped at index 0x2005, subindex 0x00*/
extern UNS8 Slave2Map7_test;		/* Mapped at index 0x2006, subindex 0x00*/
extern UNS8 Slave2Map8_test;		/* Mapped at index 0x2007, subindex 0x00*/
extern UNS8 Slave2Map9_test;		/* Mapped at index 0x2008, subindex 0x00*/
extern UNS32 Slave2Map10_test;		/* Mapped at index 0x2009, subindex 0x00*/
extern UNS16 Slave2Map11_test;		/* Mapped at index 0x200A, subindex 0x00*/
extern INTEGER16 Slave2Map12_test;		/* Mapped at index 0x200B, subindex 0x00*/
extern INTEGER16 Slave2Map13_test;		/* Mapped at index 0x200C, subindex 0x00*/

#endif // TESTSLAVE2_H
