
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTSLAVE_H
#define TESTSLAVE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 TestSlave_valueRangeTest (UNS8 typeValue, void * value);
const indextable * TestSlave_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data TestSlave_Data;
extern UNS8 SlaveMap1azee;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS8 SlaveMap2azee;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS8 SlaveMap3azee;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS8 SlaveMap4azee;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS8 SlaveMap5azee;		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS8 SlaveMap6azee;		/* Mapped at index 0x2005, subindex 0x00*/
extern UNS8 SlaveMap7azee;		/* Mapped at index 0x2006, subindex 0x00*/
extern UNS8 SlaveMap8azee;		/* Mapped at index 0x2007, subindex 0x00*/
extern UNS8 SlaveMap9azee;		/* Mapped at index 0x2008, subindex 0x00*/
extern UNS32 SlaveMap10azee;		/* Mapped at index 0x2009, subindex 0x00*/
extern UNS16 SlaveMap11azee;		/* Mapped at index 0x200A, subindex 0x00*/
extern INTEGER16 SlaveMap12azee;		/* Mapped at index 0x200B, subindex 0x00*/
extern INTEGER16 SlaveMap13azee;		/* Mapped at index 0x200C, subindex 0x00*/

#endif // TESTSLAVE_H
