#define ERR_LASER_FATAL 0x0F

//laser_status CODE ERREUR OP
#define LASER_STATUS_OK 0x00
#define MASTER_FAILED_TIMEOUT 0x01
#define SLAVE_FAILED_TIMEOUT 0x02
#define MASTER_FAILED_DATCONSISTENCY 0x04
#define SLAVE_FAILED_DATCONSISTENCY 0x08
#define MASTER_NOT_STARTED 0x10
#define SLAVE_NOT_STARTED 0x20

//CODE ERREUR INITIALISATION
//init check Laser_Init2Laser
#define LASER_INIT_OK 0x00
#define LASER_MASTER_INIT_ERROR 0x01
#define LASER_MASTER_INIT_ERROR2 0x03
#define LASER_SLAVE_INIT_ERROR 0x04
#define LASER_SLAVE_INIT_ERROR2 0x0C
#define ERR_LASER_INIT_FATAL 0xFF

//start 2laser
#define LASER_MASTER_START_ERROR 0x11
#define LASER_SLAVE_START_ERROR 0x12
#define LASER_GETPOSOFFSET_ERROR 0x14
#define LASER_START_OK 0x00

//CODE ERREUR FERMETURE
//exit Laser_Exit2Laser
#define LASER_EXIT_OK 0x00
#define LASER_MASTER_EXIT_ERROR 0x21
#define LASER_SLAVE_EXIT_ERROR 0x22
