
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef TESTM_H
#define TESTM_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 testM_valueRangeTest (UNS8 typeValue, void * value);
const indextable * testM_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data testM_Data;

#endif // TESTM_H
