#ifndef _KEYWORD_H
#define _KEYWORD_H

void keyword_init ();
void keyword_maj();

// STYLE
#define APPLICATION_SHUTDOWN "L'application va maintenant se terminer."
#define ACTIVE "Actif"
#define ABSOLUTE "Absolue"
#define ACCELERATION "Accélération"
#define ACTUAL_STATE "Etat actuel"
#define APPLI_TITLE "Spiralling Machine Appli"
#define ARRET "Arret"
#define BACKWARD "Arrière"
#define BOX_TRANS_TITLE "Pilotage de la translation"
#define COBID "COB ID"
#define CONFIGURE "Configuration"
#define COUPLE "Couple (%)"
#define COUPLE_SLOPE "Pente de couple (pour mille/s)"
#define DECELERATION "Décélération"
#define DECELERATION_QS "QS Décélération"
#define DEFAULT "NULL"
#define DENOMINATION "Dénomination"
#define DIAL_BOX_INIT_TITLE "Erreur d'initialisation"
#define DIRECTION "Direction"
#define DELAYED "Différé"
#define ETAT "Etat"
#define FORWARD "Avant"
#define ERROR_NUMBER "Nombre d'erreur"
#define ERROR "Erreur"
#define INCREMENTATION "Position"
#define INDEX "Index"
#define INITIALIZATION "Initialization"
#define INIT_ERROR "Erreur d'initialisation"
#define INIT_RUNNING "Initialisation en cours ..."
#define INIT_SUCCESS "Initialisation réussi"
#define GO "Go"
#define HALT "Actif"
#define HELIX_STEP "Pas d'hélice"
#define IMMEDIATE "Immédiat"
#define LAB_INIT_ERROR "Le passage en mode OPERATIONEL a échoué pour l'élémént"
#define LASER "Laser"
#define LASERG "Laser Gauche"
#define LASERD "Laser Droit"
#define LASER_DIST "Distance en m"
#define LASER_TITLE "Lecture Laser"
#define LOCAL_WRITING_SUCCESS "Configuration PDOr du maitre avec succès"
#define LOCAL_WRITING_ERROR "Configuration PDOr du maitre échouée"
#define LSS_ERROR "Erreur de configuration LSS"
#define LSS_SUCCESS "Configuration LSS réussi"
#define LSS_CONF_NODE_ID_SUCCESS "Configuration du NODE ID réussi"
#define LSS_CONF_NODE_ID_ERROR "Erreur de configuration du NODE ID"
#define LSS_VENDOR_ID_SUCCESS "LSS Vendor ID Success"
#define MAX_VELOCITY "Vitesse Maximale"

#define MOTOR_COUPLE "Moteur couple"
#define MOTOR_ROT "Moteur rotation"
#define MOTOR_VEL "Moteur vitesse"
#define NO "Non"
#define NODE "Noeud"
#define NODE_INDEX "Index"
#define NOW "En cours"
#define PARAMETERS "Paramètres"
#define PLAY_SLOW "Lent"
#define PLAY_QUICK "Rapide"
#define PLAY_HALT "Pause"
#define POWER_STATE "Etat de marche"
#define POWER_STATE_ERROR "Erreur de mise en marche"
#define PROFILE_MODE "Mode"
#define READ_ABORT_ERROR "Lecture impossible"
#define READ_RUNNING "Lecture en cours ..."
#define READ_SIZE_ERROR "La taille annoncée n'est pas suffisante"
#define READ_SUCCESS "Lecture avec succés"
#define READ_TYPE_ERROR "Type non défini"
#define RELATIVE "Relatif"
#define RETURN "Retour"
#define SAVE "Sauvegarde"
#define SAVE_ABORT "La sauvegarde a échoué"
#define SAVE_SUCCESS "Les paramètres ont bien été sauvegardé"
#define SAVE_CONFIG "Souhaitez-vous mettre à jour les fichiers de configuration avec les nouveaux paramètres ?"
#define SDO_ERROR "Traitement de la SDO échoué"
#define SDO_SUCCESS "SDO traitée avec succès"
#define SDO_READING_ERROR "Erreur de lecture de SDO"
#define SDO_READING_RUNNING "Lecture de SDO en cours"
#define SDO_READING_TIMEOUT "Lecture SDO trop lente"
#define SDO_READING_SUCCESS "Lecture de SDO avec succès"
#define SDO_WRITING_RUNNING "Ecriture de SDO en cours"
#define SDO_WRITING_SUCCESS "Ecriture de SDO avec succès"
#define SDO_WRITING_ERROR "Erreur d'écriture SDO"
#define SDO_WRITING_TIMEOUT "Ecriture SDO trop lente"
#define SDO_WRITING_RELOAD "Tenter de renouveler l'écriture de la SDO"
#define START_NODE "Démarrage du noeud"
#define START_RUNNING "Demarrage des périphériques en cours ..."
#define START_SUCCESS "Demarrage des périphériques réussi"
#define START_ERROR_CONTENT "Les noeuds n'ont pas pu être démarrer normalement. Veuillez éteindre et rallumer les périphériques et relancer l'application."
#define START_ERROR_TITLE "Erreur de démarrage des noeuds"
#define STATE_CON "En connexion"
#define STATE_DISC "Déconnecté"
#define STATE_INIT "Initialisation"
#define STATE_PREP "En Préparation"
#define STATE_PREOPE "Pré-opérationel"
#define STATE_OPE "Opérationel"
#define STATE_STOP "Arrété"
#define STATE_UNK "Etat Inconnu"
#define STATE_ERROR "Erreur d'initialisation"
#define STATUT_TITLE "Status"
#define STATUT_BAR "STATUS -> "
#define STATUT "Statuts des périphériques"
#define START "Go"
#define STOP "Stop"
#define STOP_SUCCESS "Arret des périphériques réussi"
#define STOP_RUNNING "Arret des périphériques en cours ..."
#define STOP_ERROR "Erreur d'arret : "
#define SLAVE_CONFIGURATION "Configuration de l'esclave"
#define SUBINDEX "Sub-Index"
#define SWITCH_OFF_SUCCESS "Arret du périphérique réussi"
#define SWITCH_OFF_ERROR "Erreur d'arret du périphérique"
#define SWITCH_ON_ERROR "Erreur de mise en marche"
#define SWITCH_ON_SUCCESS "Démarrage du périphérique avec succès"
#define TRANSMISSION "Type de transmission"
#define TRANSLATION_TITLE "Avancée de la machine"
#define TRANSLATION_VIT_TITLE "Vitesse en m"
#define TRANSLATION_READ_INFO "Données moteurs translations"
#define ROTATION_CONTROL_TITLE "Controle de la rotation"
#define ROTATION_READ_INFO "Données moteur rotation"
#define TARGET_PROFILE "Incrementation"
#define TARGET_TORQUE "Couple"
#define TARGET_VELOCITY "Vitesse"
#define TEMPERATURE "Température"
#define TIME "Durée"
#define TORQUE_RAMP "Torque ramp"
#define TORQUE_MAX_SPEED "Torque max speed"
#define TORQUE "Couple"
#define VALUE "Valeur"
#define VOLTAGE "Tension"
#define VELOCITY "Vitesse"
#define VELOCITY_INC "Inc. Vitesse"
#define VELOCITY_SET "Control Vitesse"
#define VELOCITY_END "Vitesse d'arret"
#define VITESSE_UNIT "m/s"
#define YES "Oui"
#define WARNING "Attention"

// Motor powor state
#define NR2SON 0x01
#define SOND 0x02
#define R2SON 0x03
#define SON 0x04
#define OENABLED 0x05
#define QUICK_STOP_A 0x06
#define FAULT_REACTION_A 0x07
#define FAULT 0x08
#define NOT_DEFINED 0x00

#define NR2SON_txt "Not ready to switch ON"
#define SOND_txt "Switch ON Disabled"
#define R2SON_txt "Ready to switch ON"
#define SON_txt "Switched ON"
#define OENABLED_txt "Operation Enabled"
#define QUICK_STOP_A_txt "Quick stop active"
#define FAULT_REACTION_A_txt "Fault reaction active"
#define FAULT_txt "Fault"
#define NOT_DEFINED_txt "Non défini"

// INIT STATE
#define STATE_LSS_CONFIG 1
#define STATE_PREOP 2
#define STATE_CONFIG 3
#define STATE_OP 4
#define STATE_SON 5
#define STATE_READY 6

#define STATE_LSS_CONFIG_TXT "Configuration LSS"
#define STATE_PREOP_TXT "Pre-opérationnel"
#define STATE_CONFIG_TXT "Configuration"
#define STATE_OP_TXT "Opérationnel"
#define STATE_SON_TXT "Mise en marche"
#define STATE_READY_TXT "Pret"


// INIT STATE ERROR
#define ERROR_STATE_NULL 0
#define ERROR_STATE_LSS 1
#define ERROR_STATE_PREOP 2
#define ERROR_STATE_OP  3
#define ERROR_STATE_SON 4

#define ERROR_STATE_NULL_TXT "Pas d'erreur"
#define ERROR_STATE_LSS_TXT "Erreur LSS"
#define ERROR_STATE_PREOP_TXT "Erreur Pre-OP"
#define ERROR_STATE_OP_TXT  "Erreur OP"
#define ERROR_STATE_SON_TXT "Erreur SON"

// MOTOR ERROR CODE
#define MOTOR_ERROR_CAN_OVERRUN 0x8110
#define MOTOR_ERROR_CAN_PASSIVE 0x8120
#define MOTOR_ERROR_HEARTBEAT 0x8130
#define MOTOR_ERROR_BUSOFF_RECOVER 0x8140
#define MOTOR_ERROR_BUSOFF_PENDING 0x8141
#define MOTOR_ERROR_PDO 0x8210
#define MOTOR_ERROR_TEMP 0x4210
#define MOTOR_ERROR_IDLE 0xFF01

#define MOTOR_ERROR_CAN_OVERRUN_TXT "CAN network overrun"
#define MOTOR_ERROR_CAN_PASSIVE_TXT "CAN in error passive mode"
#define MOTOR_ERROR_HEARTBEAT_TXT "Heartbeat error"
#define MOTOR_ERROR_BUSOFF_RECOVER_TXT "Reset depuis l'état BUSOFF"
#define MOTOR_ERROR_BUSOFF_PENDING_TXT "Etat BUSOFF"
#define MOTOR_ERROR_PDO_TXT "Erreur de PDO"
#define MOTOR_ERROR_TEMP_TXT "Erreur de température"
#define MOTOR_ERROR_IDLE_TXT "Erreur Idle"

// CONSTANTS
#define MAX_SDO_ERROR 2
#define SDO_TIMEOUT 3

// ERROR TITLE
#define ERR_DRIVER_UP_TITLE "Chargement du driver"
#define ERR_DRIVER_LOAD_TITLE "Chargement de la librairie"
#define ERR_DRIVER_OPEN_TITLE "Ouverture du bus"
#define ERR_FILE_CONFIG_GEN_TITLE "Génération du fichier de configuration"
#define ERR_INIT_LOOP_RUN_TITLE "Boucle d'initialisation"
#define ERR_GUI_LOOP_RUN_TITLE "Interface graphique"
#define ERR_MASTER_STOP_SYNC_TITLE "Synchronisation"
#define ERR_MASTER_START_SYNC_TITLE "Synchronisation"
#define ERR_MASTER_SET_PERIOD_TITLE "Période de synchronisation"
#define ERR_MASTER_SET_HB_CONS_TITLE "Heartbeat MASTER"
#define ERR_MASTER_CONFIG_PDOR1_TITLE "PDOR1 MASTER"
#define ERR_MASTER_CONFIG_PDOR2_TITLE "PDOR2 MASTER"
#define ERR_MASTER_CONFIG_PDOR3_TITLE "PDOR3 MASTER"
#define ERR_MASTER_CONFIG_PDOT1_TITLE "PDOT1 MASTER"
#define ERR_MASTER_CONFIG_TITLE  "Configuration MASTER"
#define ERR_LSS_CONFIG_TITLE  "Configuration LSS"
#define ERR_SLAVE_CONFIG_TITLE  "Configuration SLAVE"
#define ERR_SLAVE_CONFIG_HB_TITLE  "Heartbeat SLAVE"
#define ERR_SLAVE_CONFIG_PDOT1_TITLE "PDOT1 SLAVE"
#define ERR_SLAVE_CONFIG_PDOT2_TITLE "PDOT2 SLAVE"
#define ERR_SLAVE_CONFIG_PDOT3_TITLE "PDOT3 SLAVE"
#define ERR_SLAVE_CONFIG_PDOR1_TITLE "PDOR1 SLAVE"
#define ERR_SLAVE_CONFIG_ACTIVE_PDO_TITLE "PDO SLAVE"
#define ERR_SLAVE_CONFIG_CURRENT_TITLE "Courant électrique"
#define ERR_SLAVE_CONFIG_PROFILE_TITLE "Mode d'utilisation"
#define ERR_SLAVE_CONFIG_MAX_VELOCITY_TITLE "Vitesse max"
#define ERR_SLAVE_CONFIG_ACCELERATION_TITLE "Accélération"
#define ERR_SLAVE_CONFIG_DECELERATION_TITLE "Décélération"
#define ERR_SLAVE_CONFIG_DECELERATION_QS_TITLE "Décélation rapide"
#define ERR_SLAVE_CONFIG_TORQUE_TITLE "Couple"
#define ERR_SLAVE_CONFIG_TORQUE_SLOPE_TITLE "Pente du couple"
#define ERR_SLAVE_CONFIG_TORQUE_MAX_VELOCITY_TITLE "Vitesse max"
#define ERR_SLAVE_CONFIG_MOTOR_SON_TITLE "Démarrage moteur"
#define ERR_SLAVE_SAVE_CONFIG_TITLE "Sauvegarde de la configuration"
#define ERR_MOTOR_PAUSE_TITLE "Mise en pause du moteur"
#define ERR_MOTOR_RUN_TITLE "Mise en mouvement du moteur"
#define ERR_MOTOR_OFF_TITLE "Extinction du moteur"
#define ERR_LOAD_ACCELERATION_TITLE "Accélération"
#define ERR_LOAD_DECELERATION_TITLE "Décélération"
#define ERR_LOAD_DECELERATION_QS_TITLE "Décélération rapide"
#define ERR_LOAD_SLAVE_CONFIG_TITLE "Chargement de la configuration"
#define ERR_MOTOR_FORWARD_TITLE "Changement de sens"
#define ERR_MOTOR_BACKWARD_TITLE "Changement de sens"
#define ERR_ACCELERATION_SET_TITLE "Accélération"
#define ERR_VELOCITY_SET_TITLE "Vitesse"
#define ERR_ACCELERATION_SAVE_TITLE "Accélération"
#define ERR_DECELERATION_SAVE_TITLE "Décélération"
#define ERR_DECELERATION_QS_SAVE_TITLE "Décélération rapide"
#define ERR_SAVE_FILE_GEN_TITLE "Génération du fichier de configuration"
#define ERR_TORQUE_SAVE_TITLE "Couple"
#define ERR_TORQUE_SET_TITLE "Couple"
#define ERR_TORQUE_SLOPE_SAVE_TITLE "Pente de couple"
#define ERR_TORQUE_SLOPE_SET_TITLE "Pente de couple"
#define ERR_LOAD_TORQUE_TITLE "Couple"
#define ERR_LOAD_TORQUE_SLOPE_TITLE "Pente du couple"

// ERROR CONTENT
#define ERR_DRIVER_UP_CONTENT "Le chargement du driver SOCKET CAN a échoué"
#define ERR_DRIVER_LOAD_CONTENT "Le chargement de la librairie CANFESTIVAL a échoué"
#define ERR_DRIVER_OPEN_CONTENT "L'ouverture du bus can pour l'envoie d'information a échoué"
#define ERR_FILE_CONFIG_GEN_CONTENT "La génération d'un ou plusieurs fichiers de configuration a échoué"
#define ERR_INIT_LOOP_RUN_CONTENT "Le lancement de la boucle d'initialisation a échoué"
#define ERR_GUI_LOOP_RUN_CONTENT "Le lancement de l'interface graphique a échoué"
#define ERR_MASTER_STOP_SYNC_CONTENT "L'arret de la synchronisation a échoué"
#define ERR_MASTER_START_SYNC_CONTENT "Le démarrage de la synchronisation a échoué"
#define ERR_MASTER_SET_PERIOD_CONTENT "L'affectation de la période de synchronisation a échoué"
#define ERR_MASTER_SET_HB_CONS_CONTENT "L'affectation du heartbeat dans le dictionnaire du maitre a échoué"
#define ERR_MASTER_CONFIG_PDOR1_CONTENT "La configuration de la PDO1 récepteur du maitre a échoué"
#define ERR_MASTER_CONFIG_PDOR2_CONTENT "La configuration de la PDO2 récepteur du maitre a échoué"
#define ERR_MASTER_CONFIG_PDOR3_CONTENT "La configuration de la PDO3 récepteur du maitre a échoué"
#define ERR_MASTER_CONFIG_PDOT1_CONTENT "La configuration de la PDO1 transmetteur du maitre a échoué"
#define ERR_MASTER_CONFIG_CONTENT "La configuration du maitre a échoué"
#define ERR_LSS_CONFIG_CONTENT "La configuration LSS a échoué"
#define ERR_SLAVE_CONFIG_CONTENT "La configuration d'un esclave a échoué"
#define ERR_SLAVE_CONFIG_HB_CONTENT "L'affectation du heartbeat dans le dictionnaire esclave a échoué"
#define ERR_SLAVE_CONFIG_PDOT1_CONTENT "La configuration de la PDO1 transmetteur de l'esclave a échoué"
#define ERR_SLAVE_CONFIG_PDOT2_CONTENT "La configuration de la PDO2 transmetteur de l'esclave a échoué"
#define ERR_SLAVE_CONFIG_PDOT3_CONTENT "La configuration de la PDO3 transmetteur de l'esclave a échoué"
#define ERR_SLAVE_CONFIG_PDOR1_CONTENT  "La configuration de la PDO1 recepteur de l'esclave a échoué"
#define ERR_SLAVE_CONFIG_ACTIVE_PDO_CONTENT "L'activation d'une PDO a échoué"
#define ERR_SLAVE_CONFIG_CURRENT_CONTENT "L'affectation du courant électrique de fonctionnement pour un esclave a échoué"
#define ERR_SLAVE_CONFIG_PROFILE_CONTENT "L'affectation du mode d'utilisation pour un esclave a échoué"
#define ERR_SLAVE_CONFIG_MAX_VELOCITY_CONTENT "L'affectation de la vitesse max pour un esclave a échoué"
#define ERR_SLAVE_CONFIG_ACCELERATION_CONTENT "L'affectation de l'accélération pour un esclave a échoué"
#define ERR_SLAVE_CONFIG_DECELERATION_CONTENT "L'affectation de la décélération pour un esclave a échoué"
#define ERR_SLAVE_CONFIG_DECELERATION_QS_CONTENT "L'affectation de la décélération rapide pour un esclave a échoué"
#define ERR_SLAVE_CONFIG_TORQUE_CONTENT "L'affectation du couple pour un esclave a échoué"
#define ERR_SLAVE_CONFIG_TORQUE_SLOPE_CONTENT "L'affectation de la pente de montée en couple pour un esclave a échoué"
#define ERR_SLAVE_CONFIG_TORQUE_MAX_VELOCITY_CONTENT "L'affectation de vitesse max en mode couple pour un esclave a échoué"
#define ERR_SLAVE_CONFIG_MOTOR_SON_CONTENT "La mise en marche d'un esclave a échoué"
#define ERR_SLAVE_SAVE_CONFIG_CONTENT "La sauvegarde des paramètres de configuration a échoué pour un des esclaves"
#define ERR_MOTOR_PAUSE_CONTENT "La mise en pause d'un 'des moteurs a échoué"
#define ERR_MOTOR_RUN_CONTENT "La mise en mouvement d'un des moteurs a échoué"
#define ERR_MOTOR_OFF_CONTENT "L'extinction d'un des moteurs a échoué"
#define ERR_LOAD_ACCELERATION_CONTENT "La lecture de l'accélération d'un des moteurs a échoué"
#define ERR_LOAD_DECELERATION_CONTENT "La lecture de la décélération d'un des moteurs a échoué"
#define ERR_LOAD_DECELERATION_QS_CONTENT  "La lecture de la décélération rapide d'un des moteurs a échoué"
#define ERR_LOAD_SLAVE_CONFIG_CONTENT "La lecture des paramètres de configuration a échoué"
#define ERR_MOTOR_FORWARD_CONTENT "Le changement de sens du moteur vers l'avant a échoué"
#define ERR_MOTOR_BACKWARD_CONTENT "Le changement de sens du moteur vers l'arrière a échoué"
#define ERR_ACCELERATION_SET_CONTENT "L'accélération saisie est invalide"
#define ERR_VELOCITY_SET_CONTENT "La vitesse saisie est invalide"
#define ERR_ACCELERATION_SAVE_CONTENT "La sauvegarde de l'accélération a échoué"
#define ERR_DECELERATION_SAVE_CONTENT "La sauvegarde de la décélération a échoué"
#define ERR_DECELERATION_QS_SAVE_CONTENT "La sauvegarde de la décélation rapide a échoué"
#define ERR_SAVE_FILE_GEN_CONTENT "La génération des fichiers de configuration avec les nouveaux paramètres a échoué"
#define ERR_TORQUE_SAVE_CONTENT "La sauvegarde du couple a échoué"
#define ERR_TORQUE_SET_CONTENT "Le couple saisie est invalide"
#define ERR_TORQUE_SLOPE_SAVE_CONTENT "La sauvegarde de la pente de couple a échoué"
#define ERR_TORQUE_SLOPE_SET_CONTENT "La pente de couple saisie est invalide"
#define ERR_LOAD_TORQUE_CONTENT "La lecture du couple d'un des moteurs a échoué"
#define ERR_LOAD_TORQUE_SLOPE_CONTENT "La lecture de la pente de couple d'un des moteurs a échoué"

#endif // _SIGNAUX_H
