
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef SPIRALLINGMASTER_H
#define SPIRALLINGMASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 SpirallingMaster_valueRangeTest (UNS8 typeValue, void * value);
const indextable * SpirallingMaster_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data SpirallingMaster_Data;
extern UNS16 StatusWord_1;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS16 StatusWord_2;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS16 StatusWord_3;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS16 StatusWord_4;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS16 StatusWord_5;		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS16 ControlWord_1;		/* Mapped at index 0x2005, subindex 0x00*/
extern UNS16 ControlWord_2;		/* Mapped at index 0x2006, subindex 0x00*/
extern UNS16 ControlWord_3;		/* Mapped at index 0x2007, subindex 0x00*/
extern UNS16 ControlWord_4;		/* Mapped at index 0x2008, subindex 0x00*/
extern UNS16 ControlWord_5;		/* Mapped at index 0x2009, subindex 0x00*/
extern UNS16 Voltage_1;		/* Mapped at index 0x200A, subindex 0x00*/
extern UNS16 Voltage_2;		/* Mapped at index 0x200B, subindex 0x00*/
extern UNS16 Voltage_3;		/* Mapped at index 0x200C, subindex 0x00*/
extern UNS16 Voltage_4;		/* Mapped at index 0x200D, subindex 0x00*/
extern UNS16 Voltage_5;		/* Mapped at index 0x200E, subindex 0x00*/
extern UNS16 ErrCode_1;		/* Mapped at index 0x200F, subindex 0x00*/
extern UNS16 ErrCode_2;		/* Mapped at index 0x2010, subindex 0x00*/
extern UNS16 ErrCode_3;		/* Mapped at index 0x2011, subindex 0x00*/
extern UNS16 ErrCode_4;		/* Mapped at index 0x2012, subindex 0x00*/
extern UNS16 ErrCode_5;		/* Mapped at index 0x2013, subindex 0x00*/
extern INTEGER8 InternalTemp_1;		/* Mapped at index 0x2014, subindex 0x00*/
extern INTEGER8 InternalTemp_2;		/* Mapped at index 0x2015, subindex 0x00*/
extern INTEGER8 InternalTemp_3;		/* Mapped at index 0x2016, subindex 0x00*/
extern INTEGER8 InternalTemp_4;		/* Mapped at index 0x2017, subindex 0x00*/
extern INTEGER8 InternalTemp_5;		/* Mapped at index 0x2018, subindex 0x00*/
extern INTEGER32 ConsVit_T;		/* Mapped at index 0x2019, subindex 0x00*/
extern INTEGER32 ConsVit_R;		/* Mapped at index 0x201A, subindex 0x00*/
extern INTEGER32 CaptVit_T;		/* Mapped at index 0x201B, subindex 0x00*/
extern INTEGER32 CaptVit_R;		/* Mapped at index 0x201C, subindex 0x00*/
extern INTEGER32 CaptPos_R;		/* Mapped at index 0x201D, subindex 0x00*/
extern UNS32 ConsAccel_T;		/* Mapped at index 0x201E, subindex 0x00*/
extern UNS32 ConsAccel_R;		/* Mapped at index 0x201F, subindex 0x00*/
extern UNS32 CaptAccel_T;		/* Mapped at index 0x2020, subindex 0x00*/
extern UNS32 CaptAccel_R;		/* Mapped at index 0x2021, subindex 0x00*/
extern UNS32 ConsDecel_T;		/* Mapped at index 0x2022, subindex 0x00*/
extern UNS32 ConsDecel_R;		/* Mapped at index 0x2023, subindex 0x00*/
extern UNS32 CaptDecel_T;		/* Mapped at index 0x2024, subindex 0x00*/
extern UNS32 CaptDecel_R;		/* Mapped at index 0x2025, subindex 0x00*/
extern INTEGER32 Velocity_1;		/* Mapped at index 0x2026, subindex 0x00*/
extern INTEGER32 Velocity_2;		/* Mapped at index 0x2027, subindex 0x00*/
extern INTEGER32 Velocity_3;		/* Mapped at index 0x2028, subindex 0x00*/
extern INTEGER32 Velocity_4;		/* Mapped at index 0x2029, subindex 0x00*/
extern INTEGER32 Velocity_5;		/* Mapped at index 0x202A, subindex 0x00*/
extern INTEGER32 Vel2Send_1;		/* Mapped at index 0x202B, subindex 0x00*/
extern INTEGER32 Vel2Send_2;		/* Mapped at index 0x202C, subindex 0x00*/
extern INTEGER32 Vel2Send_3;		/* Mapped at index 0x202D, subindex 0x00*/
extern INTEGER32 Vel2Send_4;		/* Mapped at index 0x202E, subindex 0x00*/
extern INTEGER32 Vel2Send_5;		/* Mapped at index 0x202F, subindex 0x00*/

#endif // SPIRALLINGMASTER_H
