
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef SPIRALLINGMASTER_H
#define SPIRALLINGMASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 SpirallingMaster_valueRangeTest (UNS8 typeValue, void * value);
const indextable * SpirallingMaster_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data SpirallingMaster_Data;
extern UNS16 StatusWord_1;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS16 StatusWord_2;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS16 StatusWord_3;		/* Mapped at index 0x2002, subindex 0x00*/
extern UNS16 StatusWord_4;		/* Mapped at index 0x2003, subindex 0x00*/
extern UNS16 StatusWord_5;		/* Mapped at index 0x2004, subindex 0x00*/
extern UNS16 ErrorCode_1;		/* Mapped at index 0x2005, subindex 0x00*/
extern UNS16 ErrorCode_2;		/* Mapped at index 0x2006, subindex 0x00*/
extern UNS16 ErrorCode_3;		/* Mapped at index 0x2007, subindex 0x00*/
extern UNS16 ErrorCode_4;		/* Mapped at index 0x2008, subindex 0x00*/
extern UNS16 ErrorCode_5;		/* Mapped at index 0x2009, subindex 0x00*/
extern UNS16 Voltage_1;		/* Mapped at index 0x200A, subindex 0x00*/
extern UNS16 Voltage_2;		/* Mapped at index 0x200B, subindex 0x00*/
extern UNS16 Voltage_3;		/* Mapped at index 0x200C, subindex 0x00*/
extern UNS16 Voltage_4;		/* Mapped at index 0x200D, subindex 0x00*/
extern UNS16 Voltage_5;		/* Mapped at index 0x200E, subindex 0x00*/
extern INTEGER8 Temperature_1;		/* Mapped at index 0x200F, subindex 0x00*/
extern INTEGER8 Temperature_2;		/* Mapped at index 0x2010, subindex 0x00*/
extern INTEGER8 Temperature_3;		/* Mapped at index 0x2011, subindex 0x00*/
extern INTEGER8 Temperature_4;		/* Mapped at index 0x2012, subindex 0x00*/
extern INTEGER8 Temperature_5;		/* Mapped at index 0x2013, subindex 0x00*/
extern INTEGER32 VelocityR_1;		/* Mapped at index 0x2014, subindex 0x00*/
extern INTEGER32 VelocityR_2;		/* Mapped at index 0x2015, subindex 0x00*/
extern INTEGER32 VelocityR_3;		/* Mapped at index 0x2016, subindex 0x00*/
extern INTEGER32 VelocityR_4;		/* Mapped at index 0x2017, subindex 0x00*/
extern INTEGER32 VelocityR_5;		/* Mapped at index 0x2018, subindex 0x00*/
extern INTEGER32 VelocityS_1;		/* Mapped at index 0x2019, subindex 0x00*/
extern INTEGER32 VelocityS_2;		/* Mapped at index 0x201A, subindex 0x00*/
extern INTEGER32 VelocityS_3;		/* Mapped at index 0x201B, subindex 0x00*/
extern INTEGER32 VelocityS_4;		/* Mapped at index 0x201C, subindex 0x00*/
extern INTEGER32 VelocityS_5;		/* Mapped at index 0x201D, subindex 0x00*/
extern INTEGER32 PositionR_1;		/* Mapped at index 0x201E, subindex 0x00*/
extern INTEGER32 PositionR_2;		/* Mapped at index 0x201F, subindex 0x00*/
extern INTEGER32 PositionR_3;		/* Mapped at index 0x2020, subindex 0x00*/
extern INTEGER32 PositionR_4;		/* Mapped at index 0x2021, subindex 0x00*/
extern INTEGER32 PositionR_5;		/* Mapped at index 0x2022, subindex 0x00*/
extern UNS32 AccelerationS_1;		/* Mapped at index 0x2023, subindex 0x00*/
extern UNS32 AccelerationS_2;		/* Mapped at index 0x2024, subindex 0x00*/
extern UNS32 AccelerationS_3;		/* Mapped at index 0x2025, subindex 0x00*/
extern UNS32 AccelerationS_4;		/* Mapped at index 0x2026, subindex 0x00*/
extern UNS32 AccelerationS_5;		/* Mapped at index 0x2027, subindex 0x00*/
extern UNS32 DecelerationS_1;		/* Mapped at index 0x2028, subindex 0x00*/
extern UNS32 DecelerationS_2;		/* Mapped at index 0x2029, subindex 0x00*/
extern UNS32 DecelerationS_3;		/* Mapped at index 0x202A, subindex 0x00*/
extern UNS32 DecelerationS_4;		/* Mapped at index 0x202B, subindex 0x00*/
extern UNS32 DecelerationS_5;		/* Mapped at index 0x202C, subindex 0x00*/

#endif // SPIRALLINGMASTER_H
